### ISSUE TITLE
Where is located "myfile" from description?

### ISSUE THREAD

**Issue by david-shiko** [hfikry92/TinderBot#2]
Hello.

How to get "a text file path that contains the headers dictionary that is copied from the browser", do you know where it located in windows system for chrome browser for example?

**Comment by m8urray** [comment]
Hi @hfikry92 ,

First of all, thanks very much for creating this package. It really made learning python more fun:)

As I am following your instructions, I came across this error in Command Prompt:

>>> from TinderBot import TinderBot
>>> bot = TinderBot("myfile.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda\lib\site-packages\TinderBot.py", line 22, in __init__
    self.headers[key_val[0]] = key_val[1].replace('\n','')
IndexError: list index out of range
>>> bot.likeMany(maxLikes = 20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bot' is not defined

I have successfully installed the module, as you can see in the below: 
C:\Users\Ruan_>pip install TinderBot
Collecting TinderBot
  Downloading TinderBot-0.0.3-py3-none-any.whl (15 kB)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from TinderBot) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in d:\anaconda\lib\site-packages (from requests->TinderBot) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->TinderBot) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in d:\anaconda\lib\site-packages (from requests->TinderBot) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests->TinderBot) (2020.6.20)
Installing collected packages: TinderBot
Successfully installed TinderBot-0.0.3

And I am also attaching the myfile.text file that I used, containing the request headers.
[myfile.txt](https://github.com/hfikry92/TinderBot/files/5213241/myfile.txt)

The screenshot below shows how I pasted the headers:
<img width="800" alt="how I pasted the headers" src="https://user-images.githubusercontent.com/62522348/93004984-85d2fe00-f544-11ea-99ec-472b515ab863.png">


Would you help me find out why the error NameError: name 'bot' is not defined“ occurred, please?

Thanks a million in advance!

Ruan

**Comment by hfikry92** [comment]
I will update the Readme file with a video.
You should only copy the Request headers key-value pairs
