### ISSUE TITLE
Is the bot still works ?

### ISSUE THREAD

**Issue by Cristishor201** [hfikry92/TinderBot#3]
I seen that now you need  a session id...

**Comment by frederikme** [comment]
If you're looking for an up-to-date tinderbot which doesn't use the api of Tinder, but rather uses selenium as an automation tool, this might be of interest. https://github.com/frederikme/TinderBot

Note: this is my own project, I normally don't self-promote, but it looks like this project is not supported anymore and should be archived and I want to offer a good alternative.

**Comment by hfikry92** [comment]
It is still active, and working. A YouTube video example will be added to Readme soon. It's working with the current code
